#
# Argos Notary - A new way to secure the Software Supply Chain
#
# Copyright (C) 2019 - 2020 Rabobank Nederland
# Copyright (C) 2019 - 2021 Gerard Borst <gerard.borst@argosnotary.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: "3.1"

services:
  argos-service:
    image: argosnotary/argos-service:master-beta
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/argos
      spring.security.oauth2.client.registration.azure.clientId: client-id
      spring.security.oauth2.client.registration.azure.clientSecret: client-secret
      spring.security.oauth2.client.provider.azure.authorizationUri: http://localhost:8087/oauth2/v2.0/authorize-manual
      spring.security.oauth2.client.provider.azure.tokenUri: http://oauth-stub:8080/oauth2/v2.0/token
      spring.security.oauth2.client.provider.azure.userInfoUri: http://oauth-stub:8080/v1.0/me
      jwt.token.secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==
      auth.frontendRedirectBasePath: http://localhost:3000
      spring.security.oauth2.client.provider.google.iconUrl: /images/auth_icons/google.svg
      spring.security.oauth2.client.provider.github.iconUrl: /images/auth_icons/github.svg
      spring.security.oauth2.client.provider.azure.iconUrl: /images/auth_icons/microsoft.svg
      logging.level: DEBUG
      JAVA_OPTS: "-Xmx1g"
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  oauth-stub:
    image: argosnotary/argos-integration-test-stub:master
    ports:
      - 8087:8080

  mongodb:
    image: argosnotary/mongo:4.2.8
    ports:
      - 27017:27017

  collector-stub:
    build:
      context: docker/collector-stub
    ports:
      - 8888:8080
