---
kind: pipeline
name: argos-frontend-build
type: docker

steps:
  - name: test front-end image
    image: node:12.18
    commands:
    - npm install
    - npm test
    - npm run build
        
  - name: build and release front-end image
    image: plugins/docker
    settings:
      repo: argosnotary/argos-frontend
      auto_tag: true
      build_args:
        - VERSION=${DRONE_TAG}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
        - tag
    depends_on:
    - test front-end image
      
trigger:
  event:
    - push
    - tag
    - pull_request

