---
kind: pipeline
name: argos-frontend-build
type: docker

steps:
  - name: build
    image: rabobanknl/argos-build:latest
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - echo Hallo Allemaal
      
trigger:
  event:
    - push
    - pull_request

