---
kind: pipeline
name: argos-frontend-build
type: docker

environment:
  

steps:
  - name: test front-end image
    image: node:12.18
    commands:
    - npm install
    - npm test
    - npm run build
        
  - name: build and release front-end beta image
    image: plugins/docker
    settings:
      repo: argosnotary/argos-frontend
      tags: ${DRONE_BRANCH}-beta
      build_args:
        - VERSION=${DRONE_BRANCH}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      ref:
        include:
        - "refs/heads/master"
        - "refs/heads/release/*"
      event:
      - push
    depends_on:
    - test front-end image
    
  - name: build and release front-end image
    image: plugins/docker
    settings:
      repo: argosnotary/argos-frontend
      tags:
      - ${DRONE_TAG}
      build_args:
        - VERSION=${DRONE_TAG}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
      - tag
    depends_on:
    - test front-end image
      
trigger:
  event:
    - push
    - tag
    - pull_request

