---
kind: pipeline
name: argos-frontend-build
type: docker

steps:
  - name: build front-end image
    image: plugins/docker
    settings:
      repo: argosnotary/argos-frontend-snapshot
      tags: ${DRONE_BRANCH/\//_}${DRONE_TAG}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
        - push
        
  - name: build and release front-end image
    image: plugins/docker
    settings:
      repo: argosnotary/argos-frontend
      auto_tag: true
      build_args:
        - VERSION=${DRONE_TAG}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
        - tag
     
      
trigger:
  event:
    - push
    - tag

