---
kind: pipeline
type: docker
name: argos-frontend-build

platform:
  os: linux
  arch: amd64

steps:
- name: license-check
  image: maven:3.6.3
  commands:
  - mvn license:check
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository

- name: test and install
  image: node:15.0.1
  commands:
  - npm install
  - npm test
  - npm run build
  environment:
    CI: false
  depends_on:
  - license-check

- name: build and release front-end image
  image: plugins/docker
  settings:
    build_args:
    - VERSION=${DRONE_TAG:-${DRONE_BRANCH//\//_}}
    password:
      from_secret: docker_login_token
    repo: argosnotary/argos-frontend
    tags: ${DRONE_TAG:-${DRONE_BRANCH//\//_}}
    username:
      from_secret: docker_login_user
  when:
    event:
    - push
    - tag
    ref:
    - refs/heads/master
    - refs/heads/release/*
  depends_on:
  - test and install
  
- name: slack on success
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  depends_on:
  - test and install
  - build and release front-end image

volumes:
- name: mvn_cache
  host:
    path: /datadisk/mvn

trigger:
  event:
  - push
  - tag
  - pull_request

---
kind: pipeline
type: docker
name: report result

platform:
  os: linux
  arch: amd64

steps:
- name: slack on failure
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook

trigger:
  status:
  - failure
  event:
  - push
  - tag
  - pull_request

depends_on:
- argos-frontend-build

---
kind: signature
hmac: 2ee3908fe919cce4a45f0398f39e0a57bdc6bbc592095c6b53712165d445965b

...
