---
kind: pipeline
name: argos-frontend-build
type: docker

steps:
  - name: build front-end image
    image: plugins/docker
    settings:
      repo: rabobanknl/argos-frontend
      tags: ${DRONE_BRANCH}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
      
trigger:
  event:
    - push
    - pull_request

